theme: jekyll-theme-cayman
show_downloads: true

# About/contact
email: monteirocamponogara@gmail.com
description: Kinematic Algorithm for a TurtleBot in a Maze Environment
author: Lucas Camponogara Viera
github_username: camponogaraviera
